-- ============================================================================
-- FLOWBRIDGE DEV - SILVER STAR SCHEMA PIPELINE
-- Snowflake
-- ============================================================================

USE ROLE SYSADMIN;
USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;
USE WAREHOUSE FLOWBRIDGE_PIPELINE_WH;


-- ============================================================================
-- 1. SURROGATE KEY SEQUENCES
-- ============================================================================

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.DIM_CUSTOMER_SK_SEQ
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.DIM_PRODUCT_SK_SEQ
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.DIM_SUPPLIER_SK_SEQ
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.DIM_WAREHOUSE_SK_SEQ
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.DIM_SHIPMENT_SK_SEQ
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SILVER_SCH.FACT_ORDERS_SK_SEQ
    START = 1
    INCREMENT = 1;


-- ============================================================================
-- 2. CUSTOMER DIMENSION
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.DIM_CUSTOMER (
    CUSTOMER_SK NUMBER DEFAULT SILVER_SCH.DIM_CUSTOMER_SK_SEQ.NEXTVAL,
    CUSTOMER_ID STRING NOT NULL,
    CUSTOMER_NAME STRING NOT NULL,
    CUSTOMER_REGION STRING NOT NULL,
    CUSTOMER_SEGMENT STRING NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Customer dimension - Star schema - SCD Type 1';


-- ============================================================================
-- 3. PRODUCT DIMENSION
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.DIM_PRODUCT (
    PRODUCT_SK NUMBER DEFAULT SILVER_SCH.DIM_PRODUCT_SK_SEQ.NEXTVAL,
    PRODUCT_ID STRING NOT NULL,
    PRODUCT_NAME STRING NOT NULL,
    CATEGORY STRING NOT NULL,
    UNIT_PRICE FLOAT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Product dimension - Star schema - SCD Type 1';


-- ============================================================================
-- 4. SUPPLIER DIMENSION
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.DIM_SUPPLIER (
    SUPPLIER_SK NUMBER DEFAULT SILVER_SCH.DIM_SUPPLIER_SK_SEQ.NEXTVAL,
    SUPPLIER_ID STRING NOT NULL,
    SUPPLIER_NAME STRING NOT NULL,
    SUPPLIER_COUNTRY STRING NOT NULL,
    LEAD_TIME_DAYS NUMBER NOT NULL,
    PERFORMANCE_SCORE FLOAT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Supplier dimension - Star schema - SCD Type 1';


-- ============================================================================
-- 5. WAREHOUSE DIMENSION
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.DIM_WAREHOUSE (
    WAREHOUSE_SK NUMBER DEFAULT SILVER_SCH.DIM_WAREHOUSE_SK_SEQ.NEXTVAL,
    WAREHOUSE_ID STRING NOT NULL,
    WAREHOUSE_LOCATION STRING NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Warehouse dimension - Star schema - SCD Type 1';


-- ============================================================================
-- 6. SHIPMENT DIMENSION
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.DIM_SHIPMENT (
    SHIPMENT_SK NUMBER DEFAULT SILVER_SCH.DIM_SHIPMENT_SK_SEQ.NEXTVAL,
    SHIPMENT_ID STRING NOT NULL,
    CARRIER STRING NOT NULL,
    SHIP_DATE TIMESTAMP_NTZ,
    ESTIMATED_DELIVERY DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Shipment dimension - Star schema - SCD Type 1';


-- ============================================================================
-- 7. FACT ORDERS
-- ============================================================================

CREATE OR REPLACE TABLE SILVER_SCH.FACT_ORDERS (
    ORDER_SK NUMBER DEFAULT SILVER_SCH.FACT_ORDERS_SK_SEQ.NEXTVAL,

    ORDER_ID STRING NOT NULL,

    CUSTOMER_SK NUMBER NOT NULL,
    PRODUCT_SK NUMBER NOT NULL,
    SUPPLIER_SK NUMBER NOT NULL,
    WAREHOUSE_SK NUMBER NOT NULL,
    SHIPMENT_SK NUMBER NOT NULL,

    ORDER_DATE TIMESTAMP_NTZ NOT NULL,
    ORDER_STATUS STRING NOT NULL,
    PAYMENT_STATUS STRING NOT NULL,

    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE FLOAT NOT NULL,
    TOTAL_AMOUNT FLOAT NOT NULL,
    DELAY_DAYS NUMBER NOT NULL,
    INVENTORY_LEVEL NUMBER NOT NULL,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTED_AT TIMESTAMP_NTZ
)
COMMENT = 'Fact table - one row per order';


-- ============================================================================
-- 8. STREAM ON STAGING TABLE
-- ============================================================================

CREATE OR REPLACE STREAM SILVER_SCH.STG_ORDERS_STREAM
    ON TABLE SILVER_SCH.STG_ORDERS
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'CDC stream on staging orders';


-- ============================================================================
-- 9. SILVER -> STAR SCHEMA PROCEDURE
-- ============================================================================

CREATE OR REPLACE PROCEDURE SILVER_SCH.SILVER_TO_STAR()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    -- ========================================================================
    -- STEP 1: CAPTURE STREAM DATA
    -- ========================================================================

    CREATE OR REPLACE TEMPORARY TABLE SILVER_SCH.TMP_STREAM_DATA AS

    SELECT *
    FROM SILVER_SCH.STG_ORDERS_STREAM
    WHERE METADATA$ACTION = 'INSERT';


    -- ========================================================================
    -- STEP 2: CUSTOMER DIMENSION - SCD TYPE 1
    -- ========================================================================

    MERGE INTO SILVER_SCH.DIM_CUSTOMER AS TGT

    USING (
        SELECT
            UPPER(TRIM(CUSTOMER_ID)) AS CUSTOMER_ID,
            UPPER(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
            UPPER(TRIM(CUSTOMER_REGION)) AS CUSTOMER_REGION,
            UPPER(TRIM(CUSTOMER_SEGMENT)) AS CUSTOMER_SEGMENT

        FROM SILVER_SCH.TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(CUSTOMER_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1
    ) AS SRC

    ON TGT.CUSTOMER_ID = SRC.CUSTOMER_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.CUSTOMER_NAME = SRC.CUSTOMER_NAME,
        TGT.CUSTOMER_REGION = SRC.CUSTOMER_REGION,
        TGT.CUSTOMER_SEGMENT = SRC.CUSTOMER_SEGMENT,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_REGION,
        CUSTOMER_SEGMENT
    )
    VALUES (
        SRC.CUSTOMER_ID,
        SRC.CUSTOMER_NAME,
        SRC.CUSTOMER_REGION,
        SRC.CUSTOMER_SEGMENT
    );


    -- ========================================================================
    -- STEP 3: PRODUCT DIMENSION - SCD TYPE 1
    -- ========================================================================

    MERGE INTO SILVER_SCH.DIM_PRODUCT AS TGT

    USING (
        SELECT
            UPPER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
            UPPER(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
            UPPER(TRIM(CATEGORY)) AS CATEGORY,
            UNIT_PRICE

        FROM SILVER_SCH.TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(PRODUCT_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1
    ) AS SRC

    ON TGT.PRODUCT_ID = SRC.PRODUCT_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.PRODUCT_NAME = SRC.PRODUCT_NAME,
        TGT.CATEGORY = SRC.CATEGORY,
        TGT.UNIT_PRICE = SRC.UNIT_PRICE,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        UNIT_PRICE
    )
    VALUES (
        SRC.PRODUCT_ID,
        SRC.PRODUCT_NAME,
        SRC.CATEGORY,
        SRC.UNIT_PRICE
    );


    -- ========================================================================
    -- STEP 4: SUPPLIER DIMENSION - SCD TYPE 1
    -- ========================================================================

    MERGE INTO SILVER_SCH.DIM_SUPPLIER AS TGT

    USING (
        SELECT
            UPPER(TRIM(SUPPLIER_ID)) AS SUPPLIER_ID,
            UPPER(TRIM(SUPPLIER_NAME)) AS SUPPLIER_NAME,
            UPPER(TRIM(SUPPLIER_COUNTRY)) AS SUPPLIER_COUNTRY,
            LEAD_TIME_DAYS,
            PERFORMANCE_SCORE

        FROM SILVER_SCH.TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(SUPPLIER_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1
    ) AS SRC

    ON TGT.SUPPLIER_ID = SRC.SUPPLIER_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.SUPPLIER_NAME = SRC.SUPPLIER_NAME,
        TGT.SUPPLIER_COUNTRY = SRC.SUPPLIER_COUNTRY,
        TGT.LEAD_TIME_DAYS = SRC.LEAD_TIME_DAYS,
        TGT.PERFORMANCE_SCORE = SRC.PERFORMANCE_SCORE,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        SUPPLIER_ID,
        SUPPLIER_NAME,
        SUPPLIER_COUNTRY,
        LEAD_TIME_DAYS,
        PERFORMANCE_SCORE
    )
    VALUES (
        SRC.SUPPLIER_ID,
        SRC.SUPPLIER_NAME,
        SRC.SUPPLIER_COUNTRY,
        SRC.LEAD_TIME_DAYS,
        SRC.PERFORMANCE_SCORE
    );


    -- ========================================================================
    -- STEP 5: WAREHOUSE DIMENSION - SCD TYPE 1
    -- ========================================================================

    MERGE INTO SILVER_SCH.DIM_WAREHOUSE AS TGT

    USING (
        SELECT
            UPPER(TRIM(WAREHOUSE_ID)) AS WAREHOUSE_ID,
            UPPER(TRIM(WAREHOUSE_LOCATION)) AS WAREHOUSE_LOCATION

        FROM SILVER_SCH.TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(WAREHOUSE_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1
    ) AS SRC

    ON TGT.WAREHOUSE_ID = SRC.WAREHOUSE_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.WAREHOUSE_LOCATION = SRC.WAREHOUSE_LOCATION,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        WAREHOUSE_ID,
        WAREHOUSE_LOCATION
    )
    VALUES (
        SRC.WAREHOUSE_ID,
        SRC.WAREHOUSE_LOCATION
    );


    -- ========================================================================
    -- STEP 6: SHIPMENT DIMENSION - SCD TYPE 1
    -- ========================================================================

    MERGE INTO SILVER_SCH.DIM_SHIPMENT AS TGT

    USING (
        SELECT
            UPPER(TRIM(SHIPMENT_ID)) AS SHIPMENT_ID,
            UPPER(TRIM(CARRIER)) AS CARRIER,
            SHIP_DATE,
            ESTIMATED_DELIVERY

        FROM SILVER_SCH.TMP_STREAM_DATA

        WHERE UPPER(TRIM(SHIPMENT_ID)) <> 'UNKNOWN'
          AND SHIPMENT_ID IS NOT NULL

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(SHIPMENT_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1
    ) AS SRC

    ON TGT.SHIPMENT_ID = SRC.SHIPMENT_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.CARRIER = SRC.CARRIER,
        TGT.SHIP_DATE = SRC.SHIP_DATE,
        TGT.ESTIMATED_DELIVERY = SRC.ESTIMATED_DELIVERY,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        SHIPMENT_ID,
        CARRIER,
        SHIP_DATE,
        ESTIMATED_DELIVERY
    )
    VALUES (
        SRC.SHIPMENT_ID,
        SRC.CARRIER,
        SRC.SHIP_DATE,
        SRC.ESTIMATED_DELIVERY
    );


    -- ========================================================================
    -- STEP 7: FACT ORDERS
    -- ========================================================================

    MERGE INTO SILVER_SCH.FACT_ORDERS AS TGT

    USING (
        SELECT
            UPPER(TRIM(S.ORDER_ID)) AS ORDER_ID,

            DC.CUSTOMER_SK,
            DP.PRODUCT_SK,
            DS.SUPPLIER_SK,
            DW.WAREHOUSE_SK,

            COALESCE(DSH.SHIPMENT_SK, -1) AS SHIPMENT_SK,

            S.ORDER_DATE,
            UPPER(TRIM(S.ORDER_STATUS)) AS ORDER_STATUS,
            UPPER(TRIM(S.PAYMENT_STATUS)) AS PAYMENT_STATUS,

            S.QUANTITY,
            S.UNIT_PRICE,
            S.TOTAL_AMOUNT,
            S.DELAY_DAYS,
            S.INVENTORY_LEVEL,
            S.INGESTED_AT

        FROM SILVER_SCH.TMP_STREAM_DATA S

        INNER JOIN SILVER_SCH.DIM_CUSTOMER DC
            ON DC.CUSTOMER_ID = UPPER(TRIM(S.CUSTOMER_ID))

        INNER JOIN SILVER_SCH.DIM_PRODUCT DP
            ON DP.PRODUCT_ID = UPPER(TRIM(S.PRODUCT_ID))

        INNER JOIN SILVER_SCH.DIM_SUPPLIER DS
            ON DS.SUPPLIER_ID = UPPER(TRIM(S.SUPPLIER_ID))

        INNER JOIN SILVER_SCH.DIM_WAREHOUSE DW
            ON DW.WAREHOUSE_ID = UPPER(TRIM(S.WAREHOUSE_ID))

        LEFT JOIN SILVER_SCH.DIM_SHIPMENT DSH
            ON DSH.SHIPMENT_ID = UPPER(TRIM(S.SHIPMENT_ID))

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(S.ORDER_ID))
            ORDER BY S.ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.ORDER_ID = SRC.ORDER_ID

    WHEN MATCHED THEN UPDATE SET

        TGT.CUSTOMER_SK = SRC.CUSTOMER_SK,
        TGT.PRODUCT_SK = SRC.PRODUCT_SK,
        TGT.SUPPLIER_SK = SRC.SUPPLIER_SK,
        TGT.WAREHOUSE_SK = SRC.WAREHOUSE_SK,
        TGT.SHIPMENT_SK = SRC.SHIPMENT_SK,

        TGT.ORDER_DATE = SRC.ORDER_DATE,
        TGT.ORDER_STATUS = SRC.ORDER_STATUS,
        TGT.PAYMENT_STATUS = SRC.PAYMENT_STATUS,

        TGT.QUANTITY = SRC.QUANTITY,
        TGT.UNIT_PRICE = SRC.UNIT_PRICE,
        TGT.TOTAL_AMOUNT = SRC.TOTAL_AMOUNT,
        TGT.DELAY_DAYS = SRC.DELAY_DAYS,
        TGT.INVENTORY_LEVEL = SRC.INVENTORY_LEVEL,

        TGT.INGESTED_AT = SRC.INGESTED_AT,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        ORDER_ID,
        CUSTOMER_SK,
        PRODUCT_SK,
        SUPPLIER_SK,
        WAREHOUSE_SK,
        SHIPMENT_SK,
        ORDER_DATE,
        ORDER_STATUS,
        PAYMENT_STATUS,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,
        DELAY_DAYS,
        INVENTORY_LEVEL,
        INGESTED_AT
    )
    VALUES (
        SRC.ORDER_ID,
        SRC.CUSTOMER_SK,
        SRC.PRODUCT_SK,
        SRC.SUPPLIER_SK,
        SRC.WAREHOUSE_SK,
        SRC.SHIPMENT_SK,
        SRC.ORDER_DATE,
        SRC.ORDER_STATUS,
        SRC.PAYMENT_STATUS,
        SRC.QUANTITY,
        SRC.UNIT_PRICE,
        SRC.TOTAL_AMOUNT,
        SRC.DELAY_DAYS,
        SRC.INVENTORY_LEVEL,
        SRC.INGESTED_AT
    );


    -- ========================================================================
    -- STEP 8: CLEANUP
    -- ========================================================================

    DROP TABLE IF EXISTS SILVER_SCH.TMP_STREAM_DATA;


    RETURN 'silver_to_star completed successfully';

END;
$$;


-- ============================================================================
-- 10. TASK
-- ============================================================================

CREATE OR REPLACE TASK SILVER_SCH.SILVER_TO_STAR_TASK
    WAREHOUSE = FLOWBRIDGE_PIPELINE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
    )
AS
    CALL SILVER_SCH.SILVER_TO_STAR();


-- ============================================================================
-- 11. ENABLE TASK
-- ============================================================================

ALTER TASK SILVER_SCH.SILVER_TO_STAR_TASK RESUME;


-- ============================================================================
-- 12. VERIFY STREAM
-- ============================================================================

SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS STREAM_HAS_DATA;


-- ============================================================================
-- 13. CHECK TASK
-- ============================================================================

SHOW TASKS;


-- ============================================================================
-- 14. CHECK DIMENSION + FACT COUNTS
-- ============================================================================

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SILVER_SCH.DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM SILVER_SCH.DIM_PRODUCT

UNION ALL

SELECT 'DIM_SUPPLIER', COUNT(*)
FROM SILVER_SCH.DIM_SUPPLIER

UNION ALL

SELECT 'DIM_WAREHOUSE', COUNT(*)
FROM SILVER_SCH.DIM_WAREHOUSE

UNION ALL

SELECT 'DIM_SHIPMENT', COUNT(*)
FROM SILVER_SCH.DIM_SHIPMENT

UNION ALL

SELECT 'FACT_ORDERS', COUNT(*)
FROM SILVER_SCH.FACT_ORDERS;


-- ============================================================================
-- 15. PREVIEW STAR SCHEMA
-- ============================================================================

SELECT *
FROM SILVER_SCH.DIM_CUSTOMER
LIMIT 10;

SELECT *
FROM SILVER_SCH.DIM_PRODUCT
LIMIT 10;

SELECT *
FROM SILVER_SCH.DIM_SUPPLIER
LIMIT 10;

SELECT *
FROM SILVER_SCH.DIM_WAREHOUSE
LIMIT 10;

SELECT *
FROM SILVER_SCH.DIM_SHIPMENT
LIMIT 10;

SELECT *
FROM SILVER_SCH.FACT_ORDERS
LIMIT 10;

USE ROLE SYSADMIN;
USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;
USE WAREHOUSE FLOWBRIDGE_PIPELINE_WH;

SELECT COUNT(*) AS STG_ORDERS_COUNT
FROM SILVER_SCH.STG_ORDERS;

SELECT *
FROM SILVER_SCH.STG_ORDERS
LIMIT 10;


SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS STREAM_HAS_DATA;

SELECT *
FROM SILVER_SCH.STG_ORDERS_STREAM
LIMIT 20;

CALL SILVER_SCH.SILVER_TO_STAR();   

USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;

DESC TABLE SILVER_SCH.STG_ORDERS;

SELECT *
FROM SILVER_SCH.STG_ORDERS
LIMIT 5;

DESC STREAM SILVER_SCH.STG_ORDERS_STREAM;

SELECT *
FROM SILVER_SCH.STG_ORDERS_STREAM
LIMIT 5;

DESC TABLE SILVER_SCH.STG_ORDERS;
SELECT *
FROM SILVER_SCH.STG_ORDERS
LIMIT 5;

DESC STREAM SILVER_SCH.STG_ORDERS_STREAM;


USE ROLE SYSADMIN;
USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;
USE WAREHOUSE FLOWBRIDGE_PIPELINE_WH;

CREATE OR REPLACE TEMPORARY TABLE TMP_STREAM_TEST AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    ORDER_STATUS,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_REGION,
    CUSTOMER_SEGMENT,
    SUPPLIER_ID,
    SUPPLIER_NAME,
    SUPPLIER_COUNTRY,
    LEAD_TIME_DAYS,
    PERFORMANCE_SCORE,
    SHIPMENT_ID,
    CARRIER,
    SHIP_DATE,
    ESTIMATED_DELIVERY,
    DELAY_DAYS,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    PAYMENT_STATUS,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    INVENTORY_LEVEL,
    INGESTED_AT
FROM SILVER_SCH.STG_ORDERS_STREAM
WHERE METADATA$ACTION = 'INSERT';

SELECT COUNT(*) AS STREAM_ROWS
FROM TMP_STREAM_TEST;

SELECT *
FROM TMP_STREAM_TEST
LIMIT 5;

SELECT GET_DDL(
    'PROCEDURE',
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.SILVER_TO_STAR()'
);


----------------------------------------------------------------
USE ROLE SYSADMIN;
USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;
USE WAREHOUSE FLOWBRIDGE_PIPELINE_WH;


CREATE OR REPLACE PROCEDURE SILVER_SCH.SILVER_TO_STAR()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    -- ================================================================
    -- 1. CAPTURE STREAM DATA
    -- ================================================================

    CREATE OR REPLACE TEMPORARY TABLE TMP_STREAM_DATA AS
    SELECT
        ORDER_ID,
        ORDER_DATE,
        ORDER_STATUS,

        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_REGION,
        CUSTOMER_SEGMENT,

        SUPPLIER_ID,
        SUPPLIER_NAME,
        SUPPLIER_COUNTRY,
        LEAD_TIME_DAYS,
        PERFORMANCE_SCORE,

        SHIPMENT_ID,
        CARRIER,
        SHIP_DATE,
        ESTIMATED_DELIVERY,
        DELAY_DAYS,

        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,

        PAYMENT_STATUS,

        WAREHOUSE_ID,
        WAREHOUSE_LOCATION,
        INVENTORY_LEVEL,

        INGESTED_AT

    FROM SILVER_SCH.STG_ORDERS_STREAM

    WHERE METADATA$ACTION = 'INSERT';


    -- ================================================================
    -- 2. CUSTOMER DIMENSION
    -- ================================================================

    MERGE INTO SILVER_SCH.DIM_CUSTOMER AS TGT

    USING (
        SELECT
            UPPER(TRIM(CUSTOMER_ID)) AS CUSTOMER_ID,
            UPPER(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
            UPPER(TRIM(CUSTOMER_REGION)) AS CUSTOMER_REGION,
            UPPER(TRIM(CUSTOMER_SEGMENT)) AS CUSTOMER_SEGMENT

        FROM TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(CUSTOMER_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.CUSTOMER_ID = SRC.CUSTOMER_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.CUSTOMER_NAME = SRC.CUSTOMER_NAME,
        TGT.CUSTOMER_REGION = SRC.CUSTOMER_REGION,
        TGT.CUSTOMER_SEGMENT = SRC.CUSTOMER_SEGMENT,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_REGION,
        CUSTOMER_SEGMENT
    )
    VALUES (
        SRC.CUSTOMER_ID,
        SRC.CUSTOMER_NAME,
        SRC.CUSTOMER_REGION,
        SRC.CUSTOMER_SEGMENT
    );


    -- ================================================================
    -- 3. PRODUCT DIMENSION
    -- ================================================================

    MERGE INTO SILVER_SCH.DIM_PRODUCT AS TGT

    USING (
        SELECT
            UPPER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
            UPPER(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
            UPPER(TRIM(CATEGORY)) AS CATEGORY,
            UNIT_PRICE

        FROM TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(PRODUCT_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.PRODUCT_ID = SRC.PRODUCT_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.PRODUCT_NAME = SRC.PRODUCT_NAME,
        TGT.CATEGORY = SRC.CATEGORY,
        TGT.UNIT_PRICE = SRC.UNIT_PRICE,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        UNIT_PRICE
    )
    VALUES (
        SRC.PRODUCT_ID,
        SRC.PRODUCT_NAME,
        SRC.CATEGORY,
        SRC.UNIT_PRICE
    );


    -- ================================================================
    -- 4. SUPPLIER DIMENSION
    -- ================================================================

    MERGE INTO SILVER_SCH.DIM_SUPPLIER AS TGT

    USING (
        SELECT
            UPPER(TRIM(SUPPLIER_ID)) AS SUPPLIER_ID,
            UPPER(TRIM(SUPPLIER_NAME)) AS SUPPLIER_NAME,
            UPPER(TRIM(SUPPLIER_COUNTRY)) AS SUPPLIER_COUNTRY,
            LEAD_TIME_DAYS,
            PERFORMANCE_SCORE

        FROM TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(SUPPLIER_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.SUPPLIER_ID = SRC.SUPPLIER_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.SUPPLIER_NAME = SRC.SUPPLIER_NAME,
        TGT.SUPPLIER_COUNTRY = SRC.SUPPLIER_COUNTRY,
        TGT.LEAD_TIME_DAYS = SRC.LEAD_TIME_DAYS,
        TGT.PERFORMANCE_SCORE = SRC.PERFORMANCE_SCORE,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        SUPPLIER_ID,
        SUPPLIER_NAME,
        SUPPLIER_COUNTRY,
        LEAD_TIME_DAYS,
        PERFORMANCE_SCORE
    )
    VALUES (
        SRC.SUPPLIER_ID,
        SRC.SUPPLIER_NAME,
        SRC.SUPPLIER_COUNTRY,
        SRC.LEAD_TIME_DAYS,
        SRC.PERFORMANCE_SCORE
    );


    -- ================================================================
    -- 5. WAREHOUSE DIMENSION
    -- ================================================================

    MERGE INTO SILVER_SCH.DIM_WAREHOUSE AS TGT

    USING (
        SELECT
            UPPER(TRIM(WAREHOUSE_ID)) AS WAREHOUSE_ID,
            UPPER(TRIM(WAREHOUSE_LOCATION)) AS WAREHOUSE_LOCATION

        FROM TMP_STREAM_DATA

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(WAREHOUSE_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.WAREHOUSE_ID = SRC.WAREHOUSE_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.WAREHOUSE_LOCATION = SRC.WAREHOUSE_LOCATION,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        WAREHOUSE_ID,
        WAREHOUSE_LOCATION
    )
    VALUES (
        SRC.WAREHOUSE_ID,
        SRC.WAREHOUSE_LOCATION
    );


    -- ================================================================
    -- 6. SHIPMENT DIMENSION
    -- ================================================================

    MERGE INTO SILVER_SCH.DIM_SHIPMENT AS TGT

    USING (
        SELECT
            UPPER(TRIM(SHIPMENT_ID)) AS SHIPMENT_ID,
            UPPER(TRIM(CARRIER)) AS CARRIER,
            SHIP_DATE,
            ESTIMATED_DELIVERY

        FROM TMP_STREAM_DATA

        WHERE SHIPMENT_ID IS NOT NULL
          AND UPPER(TRIM(SHIPMENT_ID)) <> 'UNKNOWN'

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(SHIPMENT_ID))
            ORDER BY ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.SHIPMENT_ID = SRC.SHIPMENT_ID

    WHEN MATCHED THEN UPDATE SET
        TGT.CARRIER = SRC.CARRIER,
        TGT.SHIP_DATE = SRC.SHIP_DATE,
        TGT.ESTIMATED_DELIVERY = SRC.ESTIMATED_DELIVERY,
        TGT.IS_ACTIVE = TRUE,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        SHIPMENT_ID,
        CARRIER,
        SHIP_DATE,
        ESTIMATED_DELIVERY
    )
    VALUES (
        SRC.SHIPMENT_ID,
        SRC.CARRIER,
        SRC.SHIP_DATE,
        SRC.ESTIMATED_DELIVERY
    );


    -- ================================================================
    -- 7. FACT ORDERS
    -- ================================================================

    MERGE INTO SILVER_SCH.FACT_ORDERS AS TGT

    USING (
        SELECT
            UPPER(TRIM(S.ORDER_ID)) AS ORDER_ID,

            DC.CUSTOMER_SK,
            DP.PRODUCT_SK,
            DS.SUPPLIER_SK,
            DW.WAREHOUSE_SK,

            COALESCE(DSH.SHIPMENT_SK, -1) AS SHIPMENT_SK,

            S.ORDER_DATE,
            UPPER(TRIM(S.ORDER_STATUS)) AS ORDER_STATUS,
            UPPER(TRIM(S.PAYMENT_STATUS)) AS PAYMENT_STATUS,

            S.QUANTITY,
            S.UNIT_PRICE,
            S.TOTAL_AMOUNT,
            S.DELAY_DAYS,
            S.INVENTORY_LEVEL,

            S.INGESTED_AT

        FROM TMP_STREAM_DATA S

        INNER JOIN SILVER_SCH.DIM_CUSTOMER DC
            ON DC.CUSTOMER_ID = UPPER(TRIM(S.CUSTOMER_ID))

        INNER JOIN SILVER_SCH.DIM_PRODUCT DP
            ON DP.PRODUCT_ID = UPPER(TRIM(S.PRODUCT_ID))

        INNER JOIN SILVER_SCH.DIM_SUPPLIER DS
            ON DS.SUPPLIER_ID = UPPER(TRIM(S.SUPPLIER_ID))

        INNER JOIN SILVER_SCH.DIM_WAREHOUSE DW
            ON DW.WAREHOUSE_ID = UPPER(TRIM(S.WAREHOUSE_ID))

        LEFT JOIN SILVER_SCH.DIM_SHIPMENT DSH
            ON DSH.SHIPMENT_ID = UPPER(TRIM(S.SHIPMENT_ID))

        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(S.ORDER_ID))
            ORDER BY S.ORDER_DATE DESC
        ) = 1

    ) AS SRC

    ON TGT.ORDER_ID = SRC.ORDER_ID

    WHEN MATCHED THEN UPDATE SET

        TGT.CUSTOMER_SK = SRC.CUSTOMER_SK,
        TGT.PRODUCT_SK = SRC.PRODUCT_SK,
        TGT.SUPPLIER_SK = SRC.SUPPLIER_SK,
        TGT.WAREHOUSE_SK = SRC.WAREHOUSE_SK,
        TGT.SHIPMENT_SK = SRC.SHIPMENT_SK,

        TGT.ORDER_DATE = SRC.ORDER_DATE,
        TGT.ORDER_STATUS = SRC.ORDER_STATUS,
        TGT.PAYMENT_STATUS = SRC.PAYMENT_STATUS,

        TGT.QUANTITY = SRC.QUANTITY,
        TGT.UNIT_PRICE = SRC.UNIT_PRICE,
        TGT.TOTAL_AMOUNT = SRC.TOTAL_AMOUNT,
        TGT.DELAY_DAYS = SRC.DELAY_DAYS,
        TGT.INVENTORY_LEVEL = SRC.INVENTORY_LEVEL,

        TGT.INGESTED_AT = SRC.INGESTED_AT,
        TGT.UPDATED_AT = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT (
        ORDER_ID,
        CUSTOMER_SK,
        PRODUCT_SK,
        SUPPLIER_SK,
        WAREHOUSE_SK,
        SHIPMENT_SK,
        ORDER_DATE,
        ORDER_STATUS,
        PAYMENT_STATUS,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,
        DELAY_DAYS,
        INVENTORY_LEVEL,
        INGESTED_AT
    )
    VALUES (
        SRC.ORDER_ID,
        SRC.CUSTOMER_SK,
        SRC.PRODUCT_SK,
        SRC.SUPPLIER_SK,
        SRC.WAREHOUSE_SK,
        SRC.SHIPMENT_SK,
        SRC.ORDER_DATE,
        SRC.ORDER_STATUS,
        SRC.PAYMENT_STATUS,
        SRC.QUANTITY,
        SRC.UNIT_PRICE,
        SRC.TOTAL_AMOUNT,
        SRC.DELAY_DAYS,
        SRC.INVENTORY_LEVEL,
        SRC.INGESTED_AT
    );


    -- ================================================================
    -- 8. CLEANUP
    -- ================================================================

    DROP TABLE IF EXISTS TMP_STREAM_DATA;

    RETURN 'silver_to_star completed successfully';

END;
$$;


SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SILVER_SCH.DIM_CUSTOMER

UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*)
FROM SILVER_SCH.DIM_PRODUCT

UNION ALL
SELECT 'DIM_SUPPLIER', COUNT(*)
FROM SILVER_SCH.DIM_SUPPLIER

UNION ALL
SELECT 'DIM_WAREHOUSE', COUNT(*)
FROM SILVER_SCH.DIM_WAREHOUSE

UNION ALL
SELECT 'DIM_SHIPMENT', COUNT(*)
FROM SILVER_SCH.DIM_SHIPMENT

UNION ALL
SELECT 'FACT_ORDERS', COUNT(*)
FROM SILVER_SCH.FACT_ORDERS;

SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS HAS_DATA;

USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;

SELECT COUNT(*) AS STG_ROWS
FROM SILVER_SCH.STG_ORDERS;

CREATE OR REPLACE STREAM SILVER_SCH.STG_ORDERS_STREAM
    ON TABLE SILVER_SCH.STG_ORDERS
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'Stream on stg_orders';

SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS HAS_DATA;

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    SUPPLIER_ID,
    WAREHOUSE_ID,
    SHIPMENT_ID,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM SILVER_SCH.STG_ORDERS_STREAM
LIMIT 10;

CALL SILVER_SCH.SILVER_TO_STAR();


CREATE OR REPLACE TABLE SILVER_SCH.DIM_SUPPLIER (
    SUPPLIER_SK NUMBER DEFAULT DIM_SUPPLIER_SK_SEQ.NEXTVAL,
    SUPPLIER_ID STRING NOT NULL,
    SUPPLIER_NAME STRING NOT NULL,
    SUPPLIER_COUNTRY STRING NOT NULL,
    LEAD_TIME_DAYS NUMBER NOT NULL,
    PERFORMANCE_SCORE FLOAT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Supplier Dimension - star schema - surrogate key via sequence';

DESC TABLE SILVER_SCH.DIM_SUPPLIER;

SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS HAS_DATA;

USE ROLE SYSADMIN;
USE DATABASE FLOWBRIDGE_DEV_DB;
USE SCHEMA SILVER_SCH;
USE WAREHOUSE FLOWBRIDGE_PIPELINE_WH;

CREATE OR REPLACE TABLE SILVER_SCH.DIM_SUPPLIER (
    SUPPLIER_SK NUMBER DEFAULT DIM_SUPPLIER_SK_SEQ.NEXTVAL,
    SUPPLIER_ID STRING NOT NULL,
    SUPPLIER_NAME STRING NOT NULL,
    SUPPLIER_COUNTRY STRING NOT NULL,
    LEAD_TIME_DAYS NUMBER NOT NULL,
    PERFORMANCE_SCORE FLOAT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DESC TABLE SILVER_SCH.FACT_ORDERS;

ALTER TABLE SILVER_SCH.FACT_ORDERS
RENAME COLUMN WARHOUSE_SK TO WAREHOUSE_SK;


CREATE OR REPLACE STREAM SILVER_SCH.STG_ORDERS_STREAM
    ON TABLE SILVER_SCH.STG_ORDERS
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'Stream on stg_orders';

SELECT SYSTEM$STREAM_HAS_DATA(
    'FLOWBRIDGE_DEV_DB.SILVER_SCH.STG_ORDERS_STREAM'
) AS HAS_DATA;
SELECT COUNT(*) AS STREAM_ROWS
FROM SILVER_SCH.STG_ORDERS_STREAM;

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    SUPPLIER_ID,
    WAREHOUSE_ID,
    SHIPMENT_ID
FROM SILVER_SCH.STG_ORDERS_STREAM
LIMIT 5;

CALL SILVER_SCH.SILVER_TO_STAR();

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SILVER_SCH.DIM_CUSTOMER

UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*)
FROM SILVER_SCH.DIM_PRODUCT

UNION ALL
SELECT 'DIM_SUPPLIER', COUNT(*)
FROM SILVER_SCH.DIM_SUPPLIER

UNION ALL
SELECT 'DIM_WAREHOUSE', COUNT(*)
FROM SILVER_SCH.DIM_WAREHOUSE

UNION ALL
SELECT 'DIM_SHIPMENT', COUNT(*)
FROM SILVER_SCH.DIM_SHIPMENT

UNION ALL
SELECT 'FACT_ORDERS', COUNT(*)
FROM SILVER_SCH.FACT_ORDERS;

select * from silver_sch.dim_customer;
select * from silver_sch.dim_product;

select * from silver_sch.dim_supplier;

select * from silver_sch.dim_warehouse;

select * from silver_sch.dim_shipment;
select * from silver_sch.fact_orders;
