USE ROLE sysadmin;
USE WAREHOUSE flowbridge_pipeline_wh;

-- 1
ALTER PIPE flowbridge_prod_db.bronze_sch.supply_chain_pipe_prod SET pipe_execution_paused = false;

SELECT SYSTEM$PIPE_STATUS('flowbridge_prod_db.bronze_sch.supply_chain_pipe_prod');

ALTER TASK FLOWBRIDGE_PROD_DB.SILVER_SCH.BRONZE_TO_SILVER_TASK RESUME;
ALTER TASK FLOWBRIDGE_PROD_DB.SILVER_SCH.SILVER_TO_STAR_TASK RESUME;

show tasks in database FLOWBRIDGE_PROD_DB;


USE ROLE accountadmin;
ALTER ALERT flowbridge_prod_db.bronze_sch.pipeline_health_alert RESUME;
show alerts in database FLOWBRIDGE_PROD_DB;



use role sysadmin;
ALTER DYNAMIC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_BASE RESUME;
ALTER DYNAMIC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_INVENTORY_TURNOVER RESUME;
ALTER DYNAMIC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_ORDER_FULFILLMENT RESUME;
ALTER DYNAMIC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SHIPMENT_DELAYS RESUME;
ALTER DYNAMIC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SUPPLIER_PERFORMANCE RESUME;


-- 6. Verify Row Counts
SELECT 'RAW_ORDERS' AS TBL, COUNT(*) AS CNT FROM FLOWBRIDGE_PROD_DB.BRONZE_SCH.RAW_ORDERS
UNION ALL SELECT 'STG_ORDERS', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.STG_ORDERS
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_CUSTOMER
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_PRODUCT
UNION ALL SELECT 'DIM_SHIPMENT', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_SHIPMENT
UNION ALL SELECT 'DIM_SUPPLIER', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_SUPPLIER
UNION ALL SELECT 'DIM_WAREHOUSE', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_WAREHOUSE
UNION ALL SELECT 'FACT_ORDERS', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.FACT_ORDERS
UNION ALL SELECT 'DEAD_LETTER', COUNT(*) FROM FLOWBRIDGE_PROD_DB.SILVER_SCH.DEAD_LETTER
UNION ALL SELECT 'AGG_BASE', COUNT(*) FROM FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_BASE
UNION ALL SELECT 'AGG_INVENTORY_TURNOVER', COUNT(*) FROM FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_INVENTORY_TURNOVER
UNION ALL SELECT 'AGG_ORDER_FULFILLMENT', COUNT(*) FROM FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_ORDER_FULFILLMENT
UNION ALL SELECT 'AGG_SHIPMENT_DELAYS', COUNT(*) FROM FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SHIPMENT_DELAYS
UNION ALL SELECT 'AGG_SUPPLIER_PERFORMANCE', COUNT(*) FROM FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SUPPLIER_PERFORMANCE;

-- 7. Verify Secure Views
SELECT * FROM FLOWBRIDGE_PROD_DB.SERVING_SCH.VW_INVENTORY_TURNOVER;
SELECT * FROM FLOWBRIDGE_PROD_DB.SERVING_SCH.VW_ORDER_FULFILLMENT;
SELECT * FROM FLOWBRIDGE_PROD_DB.SERVING_SCH.VW_SHIPMENT_DELAYS;
SELECT * FROM FLOWBRIDGE_PROD_DB.SERVING_SCH.VW_SUPPLIER_PERFORMANCE;

DESC TABLE FLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_BASE;





